name: Update JSON

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Check for changes
      id: check_changes
      run: |
        git diff-index --quiet HEAD || echo "Changes found"

    - name: Update JSON
      if: steps.check_changes.outputs.changes == 'Changes found'
      run: |
        echo '[]' > dados.json
        git add dados.json
        git commit -m "Update JSON [skip ci]"
        git push https://${{ secrets.GH_TOKEN }}@github.com/Lusca-LJ12/Nomes-Salvos.git
